In [4]:
# 1. 길이가 10인 0-벡터를 만드세요.

import numpy as np  

np.zeros(shape=(10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

vector = np.zeros(shape=(10))
vector[4] = 1
print(vector)

print(np.where(np.arange(10)==4,1,0))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 0 0 0]


In [16]:
# 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.

np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
# 4. 위(3번) 벡터의 순서를 바꾸세요.

np.arange(50, 9, -1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

In [23]:
# 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

test_array = np.arange(0,9).reshape(3,3)
print(test_array)

print(np.arange(9).reshape(3 ,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

x = np.array([1,2,0,0,4,0])
y = x[x > 0]
print(y)

[1 2 4]


In [10]:
# 7. 3x3 단위 행렬(identity matrix)을 만드세요

np.identity(n=3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# 8. 난수 원소를 가지는 3x3 행렬을 만드세요
np.random.seed(seed=1000) 
b = np.random.rand(3,3)
b

array([[0.65358959, 0.11500694, 0.95028286],
       [0.4821914 , 0.87247454, 0.21233268],
       [0.04070962, 0.39719446, 0.2331322 ]])

In [14]:
# 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

print(np.max(b), np.min(b))


print(b[np.argmax(b)//3, np.argmax(b)%3],np.argmax(b))
print(b[np.argmin(b)//3, np.argmin(b)%3],np.argmin(b))

0.9502828643490245 0.040709624769089126
0.9502828643490245 2
0.040709624769089126 6


In [26]:
# 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

b.mean(axis=1), b.mean(axis=0)

(array([0.5729598 , 0.52233287, 0.22367876]),
 array([0.39216354, 0.46155865, 0.46524925]))